
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package th.tamkungz.sdvf.init;

import th.tamkungz.sdvf.item.VegetableMedleyItem;
import th.tamkungz.sdvf.item.TroutSoupItem;
import th.tamkungz.sdvf.item.TropicalCurryItem;
import th.tamkungz.sdvf.item.TripleShotEspressoItem;
import th.tamkungz.sdvf.item.TortillaItem;
import th.tamkungz.sdvf.item.TomKhaSoupItem;
import th.tamkungz.sdvf.item.SurvivalBurgerItem;
import th.tamkungz.sdvf.item.SuperMealItem;
import th.tamkungz.sdvf.item.SuperJojaColaItem;
import th.tamkungz.sdvf.item.StuffingItem;
import th.tamkungz.sdvf.item.StrangeBunItem;
import th.tamkungz.sdvf.item.StirFryItem;
import th.tamkungz.sdvf.item.SquidInkRavioliItem;
import th.tamkungz.sdvf.item.SpicyEelItem;
import th.tamkungz.sdvf.item.SpaghettiItem;
import th.tamkungz.sdvf.item.ShrimpCocktailItem;
import th.tamkungz.sdvf.item.SeafoamPuddingItem;
import th.tamkungz.sdvf.item.SashimiItem;
import th.tamkungz.sdvf.item.SalmonDinnerItem;
import th.tamkungz.sdvf.item.SaladItem;
import th.tamkungz.sdvf.item.RootsPlatterItem;
import th.tamkungz.sdvf.item.RoastedHazelnutsItem;
import th.tamkungz.sdvf.item.RicePuddingItem;
import th.tamkungz.sdvf.item.RhubarbPieItem;
import th.tamkungz.sdvf.item.RedPlateItem;
import th.tamkungz.sdvf.item.RadishSaladItem;
import th.tamkungz.sdvf.item.PumpkinSoupItem;
import th.tamkungz.sdvf.item.PumpkinPieItem;
import th.tamkungz.sdvf.item.PoppyseedMuffinItem;
import th.tamkungz.sdvf.item.PoiItem;
import th.tamkungz.sdvf.item.PlumPuddingItem;
import th.tamkungz.sdvf.item.PizzaItem;
import th.tamkungz.sdvf.item.PinkCakeItem;
import th.tamkungz.sdvf.item.PepperPoppersItem;
import th.tamkungz.sdvf.item.ParsnipSoupItem;
import th.tamkungz.sdvf.item.PancakesItem;
import th.tamkungz.sdvf.item.PaleBrothItem;
import th.tamkungz.sdvf.item.OmeletItem;
import th.tamkungz.sdvf.item.MinerTreatItem;
import th.tamkungz.sdvf.item.MapleBarItem;
import th.tamkungz.sdvf.item.MangoStickyRiceItem;
import th.tamkungz.sdvf.item.MakiRollItem;
import th.tamkungz.sdvf.item.LuckyLunchItem;
import th.tamkungz.sdvf.item.LobsterBisqueItem;
import th.tamkungz.sdvf.item.IceCreamItem;
import th.tamkungz.sdvf.item.HashbrownsItem;
import th.tamkungz.sdvf.item.GlazedYamsItem;
import th.tamkungz.sdvf.item.GingerAleItem;
import th.tamkungz.sdvf.item.FruitSaladItem;
import th.tamkungz.sdvf.item.FriedMushroomItem;
import th.tamkungz.sdvf.item.FriedEggItem;
import th.tamkungz.sdvf.item.FriedEelItem;
import th.tamkungz.sdvf.item.FriedCalamariItem;
import th.tamkungz.sdvf.item.FishStewItem;
import th.tamkungz.sdvf.item.FisTacoItem;
import th.tamkungz.sdvf.item.FiddleheadRisottoItem;
import th.tamkungz.sdvf.item.FarmerLunchItem;
import th.tamkungz.sdvf.item.EscargotItem;
import th.tamkungz.sdvf.item.EggplantParmesanItem;
import th.tamkungz.sdvf.item.DishOTheSeaItem;
import th.tamkungz.sdvf.item.CrispyBassItem;
import th.tamkungz.sdvf.item.CranberrySauceItem;
import th.tamkungz.sdvf.item.CranberryCandyItem;
import th.tamkungz.sdvf.item.CrabCakesItem;
import th.tamkungz.sdvf.item.CookieItem;
import th.tamkungz.sdvf.item.CompleteBreakfastItem;
import th.tamkungz.sdvf.item.ColeslawItem;
import th.tamkungz.sdvf.item.ChowderItem;
import th.tamkungz.sdvf.item.ChocolateCakeItem;
import th.tamkungz.sdvf.item.CheeseCauliflowerItem;
import th.tamkungz.sdvf.item.CarpSurpriseItem;
import th.tamkungz.sdvf.item.BruschettaItem;
import th.tamkungz.sdvf.item.BreadItem;
import th.tamkungz.sdvf.item.BlueberryTartItem;
import th.tamkungz.sdvf.item.BlackberryCobblerItem;
import th.tamkungz.sdvf.item.BeanHotpotItem;
import th.tamkungz.sdvf.item.BananaPuddingItem;
import th.tamkungz.sdvf.item.BakedFishItem;
import th.tamkungz.sdvf.item.AutumnBountyItem;
import th.tamkungz.sdvf.item.ArtichokeDipItem;
import th.tamkungz.sdvf.item.AlgaeSoupItem;
import th.tamkungz.sdvf.SdvfMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

public class SdvfModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, SdvfMod.MODID);
	public static final RegistryObject<Item> FRIED_EGG = REGISTRY.register("fried_egg", () -> new FriedEggItem());
	public static final RegistryObject<Item> OMELET = REGISTRY.register("omelet", () -> new OmeletItem());
	public static final RegistryObject<Item> SALAD = REGISTRY.register("salad", () -> new SaladItem());
	public static final RegistryObject<Item> CHEESE_CAULIFLOWER = REGISTRY.register("cheese_cauliflower", () -> new CheeseCauliflowerItem());
	public static final RegistryObject<Item> BAKED_FISH = REGISTRY.register("baked_fish", () -> new BakedFishItem());
	public static final RegistryObject<Item> PARSNIP_SOUP = REGISTRY.register("parsnip_soup", () -> new ParsnipSoupItem());
	public static final RegistryObject<Item> VEGETABLE_MEDLEY = REGISTRY.register("vegetable_medley", () -> new VegetableMedleyItem());
	public static final RegistryObject<Item> COMPLETE_BREAKFAST = REGISTRY.register("complete_breakfast", () -> new CompleteBreakfastItem());
	public static final RegistryObject<Item> FRIED_CALAMARI = REGISTRY.register("fried_calamari", () -> new FriedCalamariItem());
	public static final RegistryObject<Item> STRANGE_BUN = REGISTRY.register("strange_bun", () -> new StrangeBunItem());
	public static final RegistryObject<Item> LUCKY_LUNCH = REGISTRY.register("lucky_lunch", () -> new LuckyLunchItem());
	public static final RegistryObject<Item> FRIED_MUSHROOM = REGISTRY.register("fried_mushroom", () -> new FriedMushroomItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> BEAN_HOTPOT = REGISTRY.register("bean_hotpot", () -> new BeanHotpotItem());
	public static final RegistryObject<Item> GLAZED_YAMS = REGISTRY.register("glazed_yams", () -> new GlazedYamsItem());
	public static final RegistryObject<Item> CARP_SURPRISE = REGISTRY.register("carp_surprise", () -> new CarpSurpriseItem());
	public static final RegistryObject<Item> HASHBROWNS = REGISTRY.register("hashbrowns", () -> new HashbrownsItem());
	public static final RegistryObject<Item> PANCAKES = REGISTRY.register("pancakes", () -> new PancakesItem());
	public static final RegistryObject<Item> SALMON_DINNER = REGISTRY.register("salmon_dinner", () -> new SalmonDinnerItem());
	public static final RegistryObject<Item> FIS_TACO = REGISTRY.register("fis_taco", () -> new FisTacoItem());
	public static final RegistryObject<Item> CRISPY_BASS = REGISTRY.register("crispy_bass", () -> new CrispyBassItem());
	public static final RegistryObject<Item> PEPPER_POPPERS = REGISTRY.register("pepper_poppers", () -> new PepperPoppersItem());
	public static final RegistryObject<Item> BREAD = REGISTRY.register("bread", () -> new BreadItem());
	public static final RegistryObject<Item> TOM_KHA_SOUP = REGISTRY.register("tom_kha_soup", () -> new TomKhaSoupItem());
	public static final RegistryObject<Item> TROUT_SOUP = REGISTRY.register("trout_soup", () -> new TroutSoupItem());
	public static final RegistryObject<Item> CHOCOLATE_CAKE = REGISTRY.register("chocolate_cake", () -> new ChocolateCakeItem());
	public static final RegistryObject<Item> PINK_CAKE = REGISTRY.register("pink_cake", () -> new PinkCakeItem());
	public static final RegistryObject<Item> RHUBARB_PIE = REGISTRY.register("rhubarb_pie", () -> new RhubarbPieItem());
	public static final RegistryObject<Item> COOKIE = REGISTRY.register("cookie", () -> new CookieItem());
	public static final RegistryObject<Item> SPAGHETTI = REGISTRY.register("spaghetti", () -> new SpaghettiItem());
	public static final RegistryObject<Item> FRIED_EEL = REGISTRY.register("fried_eel", () -> new FriedEelItem());
	public static final RegistryObject<Item> SPICY_EEL = REGISTRY.register("spicy_eel", () -> new SpicyEelItem());
	public static final RegistryObject<Item> SASHIMI = REGISTRY.register("sashimi", () -> new SashimiItem());
	public static final RegistryObject<Item> MAKI_ROLL = REGISTRY.register("maki_roll", () -> new MakiRollItem());
	public static final RegistryObject<Item> TORTILLA = REGISTRY.register("tortilla", () -> new TortillaItem());
	public static final RegistryObject<Item> RED_PLATE = REGISTRY.register("red_plate", () -> new RedPlateItem());
	public static final RegistryObject<Item> EGGPLANT_PARMESAN = REGISTRY.register("eggplant_parmesan", () -> new EggplantParmesanItem());
	public static final RegistryObject<Item> RICE_PUDDING = REGISTRY.register("rice_pudding", () -> new RicePuddingItem());
	public static final RegistryObject<Item> ICE_CREAM = REGISTRY.register("ice_cream", () -> new IceCreamItem());
	public static final RegistryObject<Item> BLUEBERRY_TART = REGISTRY.register("blueberry_tart", () -> new BlueberryTartItem());
	public static final RegistryObject<Item> AUTUMN_BOUNTY = REGISTRY.register("autumn_bounty", () -> new AutumnBountyItem());
	public static final RegistryObject<Item> PUMPKIN_SOUP = REGISTRY.register("pumpkin_soup", () -> new PumpkinSoupItem());
	public static final RegistryObject<Item> SUPER_MEAL = REGISTRY.register("super_meal", () -> new SuperMealItem());
	public static final RegistryObject<Item> CRANBERRY_SAUCE = REGISTRY.register("cranberry_sauce", () -> new CranberrySauceItem());
	public static final RegistryObject<Item> STUFFING = REGISTRY.register("stuffing", () -> new StuffingItem());
	public static final RegistryObject<Item> FARMER_LUNCH = REGISTRY.register("farmer_lunch", () -> new FarmerLunchItem());
	public static final RegistryObject<Item> SURVIVAL_BURGER = REGISTRY.register("survival_burger", () -> new SurvivalBurgerItem());
	public static final RegistryObject<Item> DISH_O_THE_SEA = REGISTRY.register("dish_o_the_sea", () -> new DishOTheSeaItem());
	public static final RegistryObject<Item> MINER_TREAT = REGISTRY.register("miner_treat", () -> new MinerTreatItem());
	public static final RegistryObject<Item> ROOTS_PLATTER = REGISTRY.register("roots_platter", () -> new RootsPlatterItem());
	public static final RegistryObject<Item> TRIPLE_SHOT_ESPRESSO = REGISTRY.register("triple_shot_espresso", () -> new TripleShotEspressoItem());
	public static final RegistryObject<Item> SEAFOAM_PUDDING = REGISTRY.register("seafoam_pudding", () -> new SeafoamPuddingItem());
	public static final RegistryObject<Item> ALGAE_SOUP = REGISTRY.register("algae_soup", () -> new AlgaeSoupItem());
	public static final RegistryObject<Item> PALE_BROTH = REGISTRY.register("pale_broth", () -> new PaleBrothItem());
	public static final RegistryObject<Item> PLUM_PUDDING = REGISTRY.register("plum_pudding", () -> new PlumPuddingItem());
	public static final RegistryObject<Item> ARTICHOKE_DIP = REGISTRY.register("artichoke_dip", () -> new ArtichokeDipItem());
	public static final RegistryObject<Item> STIR_FRY = REGISTRY.register("stir_fry", () -> new StirFryItem());
	public static final RegistryObject<Item> ROASTED_HAZELNUTS = REGISTRY.register("roasted_hazelnuts", () -> new RoastedHazelnutsItem());
	public static final RegistryObject<Item> PUMPKIN_PIE = REGISTRY.register("pumpkin_pie", () -> new PumpkinPieItem());
	public static final RegistryObject<Item> RADISH_SALAD = REGISTRY.register("radish_salad", () -> new RadishSaladItem());
	public static final RegistryObject<Item> FRUIT_SALAD = REGISTRY.register("fruit_salad", () -> new FruitSaladItem());
	public static final RegistryObject<Item> BLACKBERRY_COBBLER = REGISTRY.register("blackberry_cobbler", () -> new BlackberryCobblerItem());
	public static final RegistryObject<Item> CRANBERRY_CANDY = REGISTRY.register("cranberry_candy", () -> new CranberryCandyItem());
	public static final RegistryObject<Item> BRUSCHETTA = REGISTRY.register("bruschetta", () -> new BruschettaItem());
	public static final RegistryObject<Item> COLESLAW = REGISTRY.register("coleslaw", () -> new ColeslawItem());
	public static final RegistryObject<Item> FIDDLEHEAD_RISOTTO = REGISTRY.register("fiddlehead_risotto", () -> new FiddleheadRisottoItem());
	public static final RegistryObject<Item> POPPYSEED_MUFFIN = REGISTRY.register("poppyseed_muffin", () -> new PoppyseedMuffinItem());
	public static final RegistryObject<Item> CHOWDER = REGISTRY.register("chowder", () -> new ChowderItem());
	public static final RegistryObject<Item> FISH_STEW = REGISTRY.register("fish_stew", () -> new FishStewItem());
	public static final RegistryObject<Item> ESCARGOT = REGISTRY.register("escargot", () -> new EscargotItem());
	public static final RegistryObject<Item> LOBSTER_BISQUE = REGISTRY.register("lobster_bisque", () -> new LobsterBisqueItem());
	public static final RegistryObject<Item> MAPLE_BAR = REGISTRY.register("maple_bar", () -> new MapleBarItem());
	public static final RegistryObject<Item> CRAB_CAKES = REGISTRY.register("crab_cakes", () -> new CrabCakesItem());
	public static final RegistryObject<Item> SHRIMP_COCKTAIL = REGISTRY.register("shrimp_cocktail", () -> new ShrimpCocktailItem());
	public static final RegistryObject<Item> GINGER_ALE = REGISTRY.register("ginger_ale", () -> new GingerAleItem());
	public static final RegistryObject<Item> BANANA_PUDDING = REGISTRY.register("banana_pudding", () -> new BananaPuddingItem());
	public static final RegistryObject<Item> MANGO_STICKY_RICE = REGISTRY.register("mango_sticky_rice", () -> new MangoStickyRiceItem());
	public static final RegistryObject<Item> POI = REGISTRY.register("poi", () -> new PoiItem());
	public static final RegistryObject<Item> TROPICAL_CURRY = REGISTRY.register("tropical_curry", () -> new TropicalCurryItem());
	public static final RegistryObject<Item> SQUID_INK_RAVIOLI = REGISTRY.register("squid_ink_ravioli", () -> new SquidInkRavioliItem());
	public static final RegistryObject<Item> SUPER_JOJA_COLA = REGISTRY.register("super_joja_cola", () -> new SuperJojaColaItem());
}
